### ISSUE TITLE
Failure to download all of the filles through wabbajack (always the same ones)

### ISSUE THREAD

**Issue by Nerio01** [jdsmith2816/eldersouls#90] opened 2020-05-21 02:55 UTC
**Describe the bug**
Cannot download all of the mods through Wabbajack. Mod page says the Elder Souls is up to date, so I download the latest file for it and launch it, following the guide. At the end I keep getting the the same result as shown in the screenshot. 

**To Reproduce**

1. Start Wabbajack
2. Download Elder souls .exe file
3. Setup the installation folders as the guide instructs and click Start.
4. ...
5. 90+ gigs of stuff download, and same 4 mods are shown as *failed to download*
**Expected behavior**
All download finished, followed by successful installation and fun times enjoying le amazing content

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
![Elder souls](https://user-images.githubusercontent.com/65695074/82518247-82f56d00-9b51-11ea-99fe-a9a4ad5dcc5c.jpg)

**Modlist version - don't know where to find the exact numbers, but it's definetely the latest one since I literally just downloaded it**

**No additional mods were added and no attempts to manually include the missing mods into the download folder were made**

**Comment by jdsmith2816** [comment] 2020-05-22 00:40
More than likely you failed to verify your email address after creating accounts at Lovers Lab and TESAlliance.  If that's not the case then you will manually need to download those four mods and place htem in the downloads folder before restarting the WJ installer.

If you need more assistance after the above then hop into the #elder-souls-support discord channel on the WJ discord server.  Link is in the readme.  Closing this as not a bug.

**Closed by jdsmith2816** 2020-05-22 00:40 UTC
Labels: wontfix
