### ISSUE TITLE
Infinite Loading Screen Thread

### ISSUE THREAD

**Issue by SovnSkyrim** [jdsmith2816/eldersouls#191] opened 2020-12-22 19:13 UTC
The Hall of Attainment cannot be loaded from the main entrance in the College of Winterhold courtyard, it's repeatable.
Since it's an ILS, no crashlog appears.

**Comment by jdsmith2816** [comment] 2020-12-22 21:17
Cannot seem to reproduce

**Comment by SovnSkyrim** [comment] 2020-12-23 15:30
It seems to appear only when Mirabelle Ervine is giving you the tour of the College

**Comment by jdsmith2816** [comment] 2020-12-23 21:49
Closing due to inability to reproduce on current build.

**Closed by jdsmith2816** 2020-12-23 21:49 UTC
