### ISSUE TITLE
No gold on Follower/Summon kills

### ISSUE THREAD

**Issue by MagusElise** [jdsmith2816/eldersouls#84] opened 2020-05-17 03:27 UTC
Cannot gain gold/souls on Follower or Summon kills

**To Reproduce**
Have a Summon or Follower kill an enemy and recieve no gold/souls

**Expected behavior**
GET GOLD PLS

**Modlist version**
1.14

**Did you add any additional mods?**
Ultimate Control Shceme
Serios Hotkeys

**Comment by jdsmith2816** [comment] 2020-05-22 01:17
Aye, this is due to the implementation.  The player now has in invisible perk that causes the gold to be granted on death... I'm toying with the idea of giving all summons / followers a similar perk that results in the same thing happenign but I'm not sure.  Maybe missing out on that gold balances out how easy it is to progress with summons and followers.

Thoughts?

**Comment by rshackleton** [comment] 2020-05-22 17:14
It's quite frustrating as it massively penalises a conjuration build. If your damage output is through summons then you lose out on a lot of experience.

Can it be something that is toggleable via an MCM menu? Have the option to gain based on followers, summons, etc.

Personally, I think to make it truly souls-like then any enemy that dies within a certain range should grant gold (souls) since that's how the games typically work. Sometimes you just want to kite that minotaur back to the city guards. 😅

**Comment by jdsmith2816** [comment] 2020-05-25 12:42
Thanks for the feedback Rich!  I plan to fix this one way or another when I do the next ES update... I'm just not quite sure what I'm going to do yet.  I'm working on Enderal currently then I need to do a round of quick bug fixes in RGE before coming back for a big ES update.

**Comment by jdsmith2816** [comment] 2020-05-28 16:42
I've resolved to fix this by using a cloak effect on the player extending out the width of a cell.  Any hostile enemy in range will receive a spell effect that gives you gold when it dies on matter the cause.

This will be worked on as part of the next real update.

**Comment by MagusElise** [comment] 2020-05-30 20:14
Awesome job jd! Love the dedication to this list <3

**Comment by jdsmith2816** [comment] 2020-12-29 00:51
Resolved in 1.3.1

**Closed by jdsmith2816** 2020-12-29 00:51 UTC
