### ISSUE TITLE
Ancient Lich (Forgotten Magic Mod) doesn't give gold to player on enemy's death

### ISSUE THREAD

**Issue by DaveyWar** [jdsmith2816/eldersouls#109] opened 2020-05-27 15:19 UTC
**Describe the bug**
When using the Ancient Lich spell from the Forgotten Magic mod, all enemies killed by the Lich do not grant gold to the player. Is this intended?

**To Reproduce**
1) Summon Ancient Lich
2) Allow Ancient Lich to get the kill on target.

**Expected behavior**
The player would receive gold after his summoned Lich ended his enemies.

**Modlist version v1.1.7**

**No additional mods added.**

**Comment by jdsmith2816** [comment] 2020-05-28 16:40
It's actually worse than this.  All minions and followers will steal your gold as will death by gravity for instance...  It's just an issue with the way I created this functionality.  I've learned how to fix it and plan to include it in the next real update.

Marking this as a duplicate of https://github.com/jdsmith2816/eldersouls/issues/84

**Closed by jdsmith2816** 2020-05-28 16:40 UTC
