### ISSUE TITLE
No Gold Given From Kills Using "Rip and Tear" Skill 

### ISSUE THREAD

**Issue by Shanomatic** [jdsmith2816/eldersouls#101] opened 2020-05-25 16:43 UTC
**Describe the bug**
No gold is given from enemies killed from the damage over time effect of the "Rip and Tear" skill from the two-handed skill tree. Unsure if this applies just to this skill or all damage over time.

**To Reproduce**

1. Hit enemy with a battle-axe while having the "Rip and Tear" skill
2. Let the damage over time kill the enemy. 

**Expected behavior**
Gold should be given from damage done over time, if possible. 

**Modlist version**
1.1.7

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment] 2020-05-28 16:45
This is really a duplicate of https://github.com/jdsmith2816/eldersouls/issues/84 due to the underlying causes an dwill be resolved at the same time.  Feel free to track that card as this is being closed.

**Closed by jdsmith2816** 2020-05-28 16:45 UTC
